name: ngnix_port_forwarder
description: A sample command-line application which is doing the ngnix port forwarding.
version: 1.0.0
environment:
  sdk: ^3.5.3
dependencies:
dev_dependencies:
  lints: ^4.0.0